//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testAssp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Eventos()
        {
            this.niños = new HashSet<niños>();
        }
    
        public int Clave_Evento { get; set; }
        public int Clave_grupo { get; set; }
        public int Clave_colonia { get; set; }
        public int Clave_Ciudad { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public string nombreEvento { get; set; }
        public string ubicacion { get; set; }
    
        public virtual ciudad ciudad { get; set; }
        public virtual colonia colonia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<niños> niños { get; set; }
        public virtual Grupo_vecino Grupo_vecino { get; set; }
    }
}
