//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testAssp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vecinos
    {
        public int ID_Vecino { get; set; }
        public string nombre { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public int Clave_colonia { get; set; }
        public int Clave_Ciudad { get; set; }
        public int Clave_ReyMago { get; set; }
        public int Clave_grupo { get; set; }
    
        public virtual ciudad ciudad { get; set; }
        public virtual colonia colonia { get; set; }
        public virtual Grupo_vecino Grupo_vecino { get; set; }
        public virtual Rey_Mago Rey_Mago { get; set; }
    }
}
